# no trailing slash
url: https://ishannla.github.io/blog/ # NEED TO CHANGE THIS ONCE DOMAIN CONFIGURED

# for header and meta tags
title: Ishan Narula
description: Ishan Narula Personal Blog

# set external to true if linking outside your website
# for internal, make sure to include preceding slash
nav-links:
  - name: About
    url: /
    external: false
  - name: Thoughts
    url: /thoughts
    external: false

# show blog post excerpts on blog page
excerpt_word_count: 70

# long date: April 20, 1969
long_date: true
# short date: Apr ‘69
short_date: false

# things you probably don't want to change
defaults:
  - # applies the default layout to all files in the project
    scope:
      path: ""
    values:
      layout: "default"
  - # sets is_post=true for all blog posts
    scope:
      path: ""
      type: posts
    values:
      is_post: true
permalink: /:title # so we have /about instead of /about.html, and /blog-post instead of /2019-11-22-blog-post.html
sass:
  style: compressed # compress the CSS file generated from the SCSS styles file
